# Generated by Django 2.0.2 on 2018-04-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convert',
            name='unit_from',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convert',
            name='unit_to',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
